# Generated by Django 3.2.9 on 2021-12-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaBd',
            fields=[
                ('id_aud_bd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_bd', models.CharField(max_length=20)),
                ('nombre_bd', models.CharField(max_length=20)),
                ('motor_bd', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=200)),
                ('id_servidor', models.CharField(max_length=20)),
                ('id_tipo', models.FloatField()),
                ('id_sistema', models.CharField(max_length=20)),
                ('fech_aud_bd', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_bd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRack',
            fields=[
                ('id_aud_rack', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_rack', models.CharField(max_length=20)),
                ('espacio_disponible', models.FloatField()),
                ('espacio_ocupado', models.FloatField()),
                ('espacio_total', models.FloatField()),
                ('tipo_rack', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=1)),
                ('id_sala', models.CharField(max_length=20)),
                ('fech_aud_rack', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_rack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSala',
            fields=[
                ('id_aud_sala', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_sala', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('metros_cuadrados', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('extintor', models.CharField(max_length=1)),
                ('refrigeracion_sala', models.CharField(max_length=1)),
                ('reconocimiento_huellas', models.CharField(max_length=1)),
                ('monitoreo', models.CharField(max_length=1)),
                ('pasa_cables', models.CharField(max_length=1)),
                ('fech_aud_sala', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaServicio',
            fields=[
                ('id_aud_servicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_servicio', models.FloatField()),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('id_tipo', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fech_aud_servicio', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaServidor',
            fields=[
                ('id_aud_serv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_servidor', models.CharField(max_length=20)),
                ('nombre_servidor', models.CharField(max_length=20)),
                ('sistema_operativo', models.CharField(max_length=20)),
                ('capacidad_disco', models.FloatField()),
                ('ram', models.FloatField()),
                ('garantia', models.CharField(max_length=1)),
                ('contrasena_admin', models.CharField(max_length=200)),
                ('direccion_ip', models.CharField(max_length=20)),
                ('rut_mantenedor', models.CharField(max_length=12)),
                ('id_rack', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('id_tipo', models.FloatField()),
                ('fech_aud_serv', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id_aud_sistema', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_sistema', models.CharField(max_length=20)),
                ('nombre_sistema', models.CharField(max_length=20)),
                ('lenguaje_sistema', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
                ('id_sensibilidad', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('id_nivel', models.FloatField()),
                ('fech_aud_sistema', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id_aud_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('telefono_empresa', models.FloatField()),
                ('telefono_personal', models.FloatField()),
                ('cargo', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('id_perfil', models.FloatField()),
                ('fech_aud_user', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id_bd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_bd', models.CharField(max_length=20)),
                ('motor_bd', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_doc', models.CharField(max_length=20)),
                ('archivo', models.BinaryField()),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_incidente', models.CharField(max_length=20)),
                ('nombre_incidente', models.CharField(max_length=20)),
                ('problema', models.CharField(max_length=200)),
                ('solucion', models.CharField(max_length=200)),
                ('tiempo_inactividad', models.FloatField()),
                ('responsable_solucion', models.CharField(max_length=20)),
                ('fecha_inci', models.DateField()),
            ],
            options={
                'db_table': 'incidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelSeguridad',
            fields=[
                ('id_nivel', models.FloatField(primary_key=True, serialize=False)),
                ('nivel', models.FloatField()),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nivel_seguridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelSensibilidad',
            fields=[
                ('id_sensibilidad', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_sensibilidad', models.CharField(max_length=20)),
                ('nivel', models.FloatField()),
            ],
            options={
                'db_table': 'nivel_sensibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(max_length=20)),
                ('nivel_perfil', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id_rack', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('espacio_disponible', models.FloatField()),
                ('espacio_ocupado', models.FloatField()),
                ('espacio_total', models.FloatField()),
                ('tipo_rack', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'rack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaServidor',
            fields=[
                ('id_sala', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=20)),
                ('metros_cuadrados', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('extintor', models.CharField(max_length=1)),
                ('refrigeracion_sala', models.CharField(max_length=1)),
                ('reconocimiento_huellas', models.CharField(max_length=1)),
                ('monitoreo', models.CharField(max_length=1)),
                ('pasa_cables', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'sala_servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_servidor', models.CharField(max_length=20)),
                ('sistema_operativo', models.CharField(max_length=20)),
                ('capacidad_disco', models.FloatField()),
                ('ram', models.FloatField()),
                ('garan', models.CharField(max_length=1)),
                ('contrasena_admin', models.CharField(max_length=200)),
                ('direccion_ip', models.CharField(max_length=20)),
                ('rut_mantenedor', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_sistema', models.CharField(max_length=20)),
                ('lenguaje_sistema', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
                ('ordenar', models.FloatField()),
            ],
            options={
                'db_table': 'sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBd',
            fields=[
                ('id_tipo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_bd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id_tipo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('telefono_empresa', models.FloatField()),
                ('telefono_personal', models.FloatField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysSerDet',
            fields=[
                ('id_servidor', models.OneToOneField(db_column='id_servidor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Homero.servidor')),
                ('tipo_relacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sys_ser_det',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysServDet',
            fields=[
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Homero.servicio')),
                ('tipo_relacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sys_serv_det',
                'managed': False,
            },
        ),
    ]
